# Q.1

TensorFlow primarily uses tensors as the fundamental data structure for representing and manipulating data. Tensors are multi-dimensional arrays that can hold data of various types. While tensors are the core data structure, TensorFlow also provides other data structures and abstractions for convenience and compatibility with various machine learning tasks. Here are some of the key data structures used in TensorFlow:

- **Variables:** Variables are mutable tensors that can be updated during training. They are often used to store the learnable parameters of a machine learning model, such as weights and biases. TensorFlow provides the tf.Variable class for creating and manipulating variables.

- **Sparse Tensors:** Sparse tensors are a specialized form of tensors used to efficiently represent and process sparse data, where most of the values are zero. They store only the non-zero elements along with their indices. TensorFlow provides the tf.sparse.SparseTensor class for working with sparse data.

- **Ragged Tensors:** Ragged tensors are used to handle sequences or arrays with varying lengths. Unlike regular tensors where all dimensions have fixed sizes, ragged tensors allow for dynamic lengths along one or more dimensions. TensorFlow provides the tf.RaggedTensor class for working with ragged data.

- **Datasets:** TensorFlow Datasets (TFDS) is a library that provides pre-processed datasets for machine learning tasks. It provides an abstraction for handling large-scale data efficiently by representing it as a sequence of elements. The tf.data.Dataset class is used to create, transform, and manipulate datasets in TensorFlow.

- **Queues:** Queues are used for asynchronous data loading and processing, especially when dealing with large datasets that do not fit entirely in memory. TensorFlow provides various queue implementations, such as tf.queue.FIFOQueue and tf.queue.PaddingFIFOQueue, to facilitate efficient data pipeline management.

# Q.2

**TensorFlow Constant:**

- A constant in TensorFlow represents a fixed value that remains unchanged throughout the execution of a computation graph.
- Once a constant is defined, its value cannot be modified.
- Constants are typically used for storing fixed input data or hyperparameters that do not require updating during training.
- The values of constants are known and explicitly provided during the graph construction.

Example:

In [1]:
import tensorflow as tf

x = tf.constant(5.0)
y = x * 2

print(y)

C:\Users\ASUS\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


tf.Tensor(10.0, shape=(), dtype=float32)


**TensorFlow Variable:**

- A variable in TensorFlow represents a mutable tensor that can hold values that are updated during the execution of a computation graph.
- Variables are typically used for storing learnable parameters, such as weights and biases, in machine learning models.
- The values of variables are not known initially and are usually initialized randomly or with specific initialization techniques.
- Variables can be modified and updated through operations like assignment (tf.Variable.assign) or using optimizers during training.

Example:

In [2]:
import tensorflow as tf

x = tf.Variable(5.0)
print(x)

#modifying variable
x.assign(7.0)
print(x)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=7.0>


# Q.3

In TensorFlow, matrix addition, multiplication, and element-wise operations are fundamental operations used for various tasks in machine learning and deep learning. Here's a description of these operations in TensorFlow:

**1. Matrix Addition:**

Matrix addition involves adding two matrices of the same shape element-wise. In TensorFlow, you can perform matrix addition using the `tf.add()` function or the `+` operator.

Example:
```python
import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix1, matrix2)
```

**2. Matrix Multiplication:**

Matrix multiplication is the process of multiplying two matrices to produce a new matrix. In TensorFlow, you can perform matrix multiplication using the `tf.matmul()` function or the `@` operator. Note that matrix multiplication has specific rules regarding the dimensions of the matrices being multiplied (inner dimensions must match).

Example:
```python
import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix1, matrix2)
# or equivalently
# result = matrix1 @ matrix2
```

**3. Element-Wise Operations:**

Element-wise operations involve applying an operation to each element of one or more tensors independently. TensorFlow provides element-wise operations for common mathematical functions like addition, subtraction, multiplication, division, exponentiation, etc.

Example (Element-Wise Addition):
```python
import tensorflow as tf

# Define two tensors
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

# Perform element-wise addition
result = tf.add(tensor1, tensor2)
# or equivalently
# result = tensor1 + tensor2
```

These operations are essential building blocks for constructing and training neural networks in TensorFlow. They can be used to define the mathematical computations involved in forward and backward passes during training, making it a powerful framework for various machine learning tasks.

# Q.4 to Q.8

In [3]:
import tensorflow as tf

#4: Create matrix A using random_normal
A = tf.random.normal(shape=(2, 2))
print("Matrix A using random_normal: ", A)

#5: Create matrix B using truncated_normal
B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B using truncated_normal: ", B)

#6: Create matrix C using random.normal
C = tf.random.normal(shape=(2, 2), mean=2, stddev=0.2)
print("Matrix C where values are drawn from normal distribution with mean=2 and std. dev=0.2: ", C)

#7: Perform matrix addition between A and B to get D
D = tf.add(A, B)
print("Matrix D (A + B): ", D)

#8: Perform matrix multiplication between C and D to get E
E = tf.matmul(C, D)
print("Matrix E (C * D): ", E)

Matrix A using random_normal:  tf.Tensor(
[[ 0.26873985  0.21652198]
 [ 0.923032   -0.16584253]], shape=(2, 2), dtype=float32)
Matrix B using truncated_normal:  tf.Tensor(
[[-1.5812075   0.5453054 ]
 [-1.2529873  -0.11775625]], shape=(2, 2), dtype=float32)
Matrix C where values are drawn from normal distribution with mean=2 and std. dev=0.2:  tf.Tensor(
[[2.0172217 1.8959476]
 [1.859057  1.8064196]], shape=(2, 2), dtype=float32)
Matrix D (A + B):  tf.Tensor(
[[-1.3124677   0.76182735]
 [-0.32995528 -0.28359878]], shape=(2, 2), dtype=float32)
Matrix E (C * D):  tf.Tensor(
[[-3.273116   0.9990862]
 [-3.0359898  0.903982 ]], shape=(2, 2), dtype=float32)


# Q.8 to Q.12

In [4]:
import tensorflow as tf

#8: Create matrix F using random_uniform
F = tf.random.uniform(shape=(2, 2))
print("Matrix F using random_uniform: ", F)

#9: Calculate the transpose of F to get G
G = tf.transpose(F)
print("Matrix G (Transpose of F): ", G)

#10: Calculate the element-wise exponential of F to get H
H = tf.exp(F)
print("Matrix H (Element-wise Exponential of F): ", H)

#11: Create matrix I by concatenating F and G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (Horizontal Concatenation of F and G): ", I)

#12: Create matrix J by concatenating F and H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (Vertical Concatenation of F and H): ", J)

Matrix F using random_uniform:  tf.Tensor(
[[0.8372592  0.96761835]
 [0.8917265  0.35838473]], shape=(2, 2), dtype=float32)
Matrix G (Transpose of F):  tf.Tensor(
[[0.8372592  0.8917265 ]
 [0.96761835 0.35838473]], shape=(2, 2), dtype=float32)
Matrix H (Element-wise Exponential of F):  tf.Tensor(
[[2.310027  2.6316693]
 [2.4393375 1.4310161]], shape=(2, 2), dtype=float32)
Matrix I (Horizontal Concatenation of F and G):  tf.Tensor(
[[0.8372592  0.96761835 0.8372592  0.8917265 ]
 [0.8917265  0.35838473 0.96761835 0.35838473]], shape=(2, 4), dtype=float32)
Matrix J (Vertical Concatenation of F and H):  tf.Tensor(
[[0.8372592  0.96761835]
 [0.8917265  0.35838473]
 [2.310027   2.6316693 ]
 [2.4393375  1.4310161 ]], shape=(4, 2), dtype=float32)
